Created a Bottom_Nav_Bar and navigation through its pages.
collabo-community/mobile_client pull request #7
Opened 2024-05-11 21:48 UTC by Oyebliss

**This pull request makes the following changes**

- Fixes (https://discordapp.com/channels/1148391778492354741/1148907665414684692/1237815129370791986)

**General Checklist**

- [x] Created a pages folder containing pages files used in the Bottom Navigation Bar.
- [x] Added Solar Icon dependency for easy use of icons.
- [x] updated the flutter_lint dependency
- [x] Added a bottom nav bar and made it switch screens on clicking

**Note**
The Icon Button for onboarding is not exactly same to the figma app design, reason being that the icon wasn't among, so i use the icon that was use for the web design instead.  

Ping @collabo-community/review-mobile-app ..

2024-05-11 21:48 UTC, Oyebliss commented
This PR is ready for review.

2024-07-01 03:38 UTC, Ifycode requested changes

2024-07-01 03:38 UTC, Ifycode commented on lib/main.dart
> +      home: HomePage(),
Comment out line 15 in the `main.dart` for now @Oyebliss (note: you are not to remove main.dart file or change its content).
Instead of the home page that first shows up, make the onboarding page/screen show up straight instead of people having to always click to get there.

2024-07-01 03:38 UTC, Ifycode commented on lib/pages/bottom_nav_pages/onboarding_page.dart
> +      backgroundColor: AppColors.Color_shades_white,
Nice work so far @Oyebliss 
About the `scaffold` content of all your 4 screens, I see repetition.
The only different things are the text in the Appbar and the text in the body.
Can you make the content of the scaffold into a reusable class or function?

2024-07-05 19:07 UTC, Ifycode requested changes

2024-07-05 19:07 UTC, Ifycode commented on lib/pages/bottom_nav_pages/onboarding_page.dart
> +      backgroundColor: AppColors.Color_shades_white,
@Oyebliss The repetition I talked about has not been taken care of from what I see here.
Or was your request for review a mistake?

2024-07-05 21:26 UTC, Oyebliss commented
I have rectify the repetition by creating a reusable Appbar and the body content.

this PR is ready for review @collabo-community/review-mobile-app

2024-07-05 21:56 UTC, Ifycode requested changes

2024-07-05 21:56 UTC, Ifycode commented on lib/pages/bottom_nav_pages/onboarding_page.dart
> +      backgroundColor: AppColors.Color_shades_white,
Referencing Discord comment for you: https://discord.com/channels/1148391778492354741/1257923271240974466/1258903179597447232

2024-07-06 13:07 UTC, Oyebliss commented
I have created the reusable Scaffold and putting all the component need in it.

This PR is ready for review again @collabo-community/review-mobile-app

2024-07-06 19:18 UTC, Ifycode approved these changes

2024-07-06 19:18 UTC, Ifycode commented on lib/pages/bottom_nav_pages/career_page.dart
> +      bodyContent:
Lovely @Oyebliss 
If there are any other problems/cleanups to do, we will fix it in subsequent task assignments. This works for now 😃

2024-07-06 19:19 UTC, merged