Display Project screen first
collabo-community/mobile_client pull request #9
Opened 2024-07-10 00:28 UTC by Oyebliss

**This pull request makes the following changes**

- Fixes issue (https://discordapp.com/channels/1148391778492354741/1253584233155395657/1260019224017895576)

**General Checklist**

- [x] Making the Project screen display first.
- [x] Text on the body of other screens change to "Coming Soon".

**Testing Checklist:**

- Project page/screen now shows up first instead of the onboarding screen.
- Project page/screen content is the same as before.
- The other screens have only "Coming soon" text in them.

2024-07-10 00:31 UTC, Oyebliss commented
Task (https://discordapp.com/channels/1148391778492354741/1253584233155395657/1260019224017895576) done..

This PR is ready for review @collabo-community/review-mobile-app

2024-07-10 21:47 UTC, Ifycode requested changes

2024-07-10 21:47 UTC, Ifycode commented on lib/pages/bottom_nav_pages/career_page.dart
> +      bodyContent: 'COMING SOON...',
See the issue ticket for the correct thing to write here @Oyebliss

2024-07-10 21:52 UTC, Ifycode requested changes

2024-07-10 21:52 UTC, Ifycode commented on lib/pages/bottom_nav_pages/project_page.dart
> +      bodyContent: 'Welcome to the project page, choose a project to work on.',
The project page was not meant to show up in the file changes. The issue description said to not change anything for project page.

2024-07-10 23:17 UTC, Ifycode requested changes

2024-07-10 23:17 UTC, Ifycode commented on lib/pages/bottom_nav_pages/project_page.dart
> +      bodyContent: 'Welcome to the project page, choose a project to work on 🧐.',
@Oyebliss If your project page is still showing up among your files changes, then it means you are doing something wrong.
Just go to the develop branch, get the original unchanged project page replace it with this one, add commit and push.

> It's something you can check for yourself. This is where I say the project page must not show up: https://github.com/collabo-community/mobile_client/pull/9/files

2024-07-11 07:54 UTC, Oyebliss commented on lib/pages/bottom_nav_pages/project_page.dart
> +      bodyContent: 'Welcome to the project page, choose a project to work on 🧐.',
The reason why the project page was showing among the changed before was that i removed the emoji from it which i ought not to do since project page was not to be changed.
Everything on the project screen is still the same has before now, it was due to the removal of emoji from it.

2024-07-11 08:45 UTC, Oyebliss commented on lib/pages/bottom_nav_pages/project_page.dart
> +      bodyContent: 'Welcome to the project page, choose a project to work on 🧐.',
Done and ready for review @collabo-community/review-mobile-app.

2024-07-11 20:58 UTC, Ifycode approved these changes
Very well done @Oyebliss  
Thank you.

> We have a docs that should show you how we prefer that you help us write your pull request title. See my full comment on Discord.

2024-07-11 21:07 UTC, merged

2024-07-12 00:14 UTC, Ifycode commented
@all-contributors add @Oyebliss for code